[tool.poetry]
name = "rosys"
version = "0.1.0"
description = "Modular Robot System With Elegant Automation Capabilities"
authors = ["Zauberzeug GmbH <info@zauberzeug.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/zauberzeug/rosys"
keywords = ["robot", "framework", "automation", "control", "steer"]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
nicegui = ">=1.4.24"
asyncio = "^3.4.3"
retry = "^0.9.2"
requests = "^2.25.1"
urllib3 = "^2.0.6" # https://github.com/zauberzeug/rosys/security/dependabot/31
simplejson = "^3.17.2"
pyserial = "^3.5"
aioserial = "^1.3.0"
numpy = "^1.20.1"
scipy = "^1.7.2"
opencv-python = "^4.5.5"
opencv-contrib-python = "^4.5.4"
psutil = "^5.9.0"
networkx = "^2.6.2"
more-itertools = "^8.10.0"
tabulate = "^0.8.9"
coloredlogs = "^15.0.1"
humanize = "^4.0.0"
aiocache = "^0.11.1"
ujson = "5.4.0"
msgpack = "^1.0.3"
uvloop = "^0.17.0"
dataclasses-json = "^0.5.7"
executing = "^1.0.0"
suntime = "^1.2.5"
line-profiler = "^4.0.3"
yappi = "^1.4"
pyloot = "^0.1.0"
objgraph = "^3.5.0"
imgsize = "^2.1"
ifaddr = "^0.2.0"
httpx = "^0.24.0"
matplotlib = "^3.7.2"
pyudev = ">=0.21.0"
esptool = "^4.3"
pyquaternion = "^0.9.9"
pillow = ">=10.3.0" # https://github.com/zauberzeug/rosys/security/dependabot/44
idna = ">=3.7" # https://github.com/zauberzeug/rosys/security/dependabot/45
uvicorn = "!=0.29.0" # test_examples.py fails with 0.29.0 due to persistency not correctly writting during teardown

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.5"
pytest = "^6.2.1"
pytest-watch = "^4.2.0"
pytest-flakefinder = "^1.0.0"
pytest-profiling = "^1.7.0"
pytest-asyncio = "0.19.0"
icecream = "^2.1.0"
debugpy = "^1.2.1"
py-spy = "^0.3.10"
isort = "^5.10.1"
cryptography = "^42.0.4" # https://github.com/zauberzeug/rosys/security/dependabot/42
sh = "^1.14.2"

[build-system]
requires = [
    "setuptools>=30.3.0,<50",
    "poetry-core>=1.0.0"
]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
# NOTE: changing default location of pytest_cache because the uvicorn file watcher somehow triggered too many reloads
cache_dir = "../.pytest_cache" 
testpaths = [
    "tests"
]

[tool.poetry.plugins.pytest11]
pytest-rosys = "rosys.testing.fixtures"
